class Customer {
  String id;
  String name;
  String plan;
  String joiningDate;
  String customerType;
  String companyName;
  String designation;
  String employees;
  String commodities;
  bool isSelected;
  Customer({
    required this.id,
    required this.name,
    required this.plan,
    required this.joiningDate,
    required this.customerType,
    required this.companyName,
    required this.designation,
    required this.employees,
    required this.commodities,
    this.isSelected = false,
  });
}

List<Customer> CUSTOMERS = [
  Customer(
    id: '1111000011101',
    name: 'Rahul',
    plan: 'Plan 1',
    joiningDate: '08/10/2000',
    customerType: 'Business',
    companyName: 'ABC Pvt. Ltd.',
    designation: 'Admin',
    employees: '10',
    commodities: '50',
  ),
  Customer(
    id: '1111000011102',
    name: 'Bharath',
    plan: 'Plan 1',
    joiningDate: '08/10/2000',
    customerType: 'Broker',
    companyName: 'BCD Pvt. Ltd.',
    designation: 'Admin',
    employees: '10',
    commodities: '20',
  ),
  Customer(
    id: '1111000011102',
    name: 'Bharath',
    plan: 'Plan 1',
    joiningDate: '08/10/2000',
    customerType: 'Broker',
    companyName: 'BCD Pvt. Ltd.',
    designation: 'Admin',
    employees: '10',
    commodities: '20',
  ),
  Customer(
    id: '1111000011102',
    name: 'Bharath',
    plan: 'Plan 1',
    joiningDate: '08/10/2000',
    customerType: 'Broker',
    companyName: 'BCD Pvt. Ltd.',
    designation: 'Admin',
    employees: '10',
    commodities: '20',
  ),
  Customer(
    id: '1111000011101',
    name: 'Rahul',
    plan: 'Plan 1',
    joiningDate: '08/10/2000',
    customerType: 'Business',
    companyName: 'ABC Pvt. Ltd.',
    designation: 'Admin',
    employees: '10',
    commodities: '50',
  ),
  Customer(
    id: '1111000011101',
    name: 'Rahul',
    plan: 'Plan 1',
    joiningDate: '08/10/2000',
    customerType: 'Business',
    companyName: 'ABC Pvt. Ltd.',
    designation: 'Admin',
    employees: '10',
    commodities: '50',
  ),
  Customer(
    id: '1111000011101',
    name: 'Rahul',
    plan: 'Plan 1',
    joiningDate: '08/10/2000',
    customerType: 'Business',
    companyName: 'ABC Pvt. Ltd.',
    designation: 'Admin',
    employees: '10',
    commodities: '50',
  ),
  Customer(
    id: '1111000011101',
    name: 'Rahul',
    plan: 'Plan 1',
    joiningDate: '08/10/2000',
    customerType: 'Business',
    companyName: 'ABC Pvt. Ltd.',
    designation: 'Admin',
    employees: '10',
    commodities: '50',
  ),
  Customer(
    id: '1111000011101',
    name: 'Rahul',
    plan: 'Plan 1',
    joiningDate: '08/10/2000',
    customerType: 'Business',
    companyName: 'ABC Pvt. Ltd.',
    designation: 'Admin',
    employees: '10',
    commodities: '50',
  ),
  Customer(
    id: '1111000011101',
    name: 'Rahul',
    plan: 'Plan 1',
    joiningDate: '08/10/2000',
    customerType: 'Business',
    companyName: 'ABC Pvt. Ltd.',
    designation: 'Admin',
    employees: '10',
    commodities: '50',
  ),
  Customer(
    id: '1111000011101',
    name: 'Rahul',
    plan: 'Plan 1',
    joiningDate: '08/10/2000',
    customerType: 'Business',
    companyName: 'ABC Pvt. Ltd.',
    designation: 'Admin',
    employees: '10',
    commodities: '50',
  ),
  Customer(
    id: '1111000011101',
    name: 'Rahul',
    plan: 'Plan 1',
    joiningDate: '08/10/2000',
    customerType: 'Business',
    companyName: 'ABC Pvt. Ltd.',
    designation: 'Admin',
    employees: '10',
    commodities: '50',
  ),
  Customer(
    id: '1111000011101',
    name: 'Rahul',
    plan: 'Plan 1',
    joiningDate: '08/10/2000',
    customerType: 'Business',
    companyName: 'ABC Pvt. Ltd.',
    designation: 'Admin',
    employees: '10',
    commodities: '50',
  ),
  Customer(
    id: '1111000011101',
    name: 'Rahul',
    plan: 'Plan 1',
    joiningDate: '08/10/2000',
    customerType: 'Business',
    companyName: 'ABC Pvt. Ltd.',
    designation: 'Admin',
    employees: '10',
    commodities: '50',
  ),
  Customer(
    id: '1111000011101',
    name: 'Rahul',
    plan: 'Plan 1',
    joiningDate: '08/10/2000',
    customerType: 'Business',
    companyName: 'ABC Pvt. Ltd.',
    designation: 'Admin',
    employees: '10',
    commodities: '50',
  ),
];
